on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - run: |
          echo '${{ steps.create_release.outputs.upload_url }}' > upload_url
      - uses: actions/upload-artifact@v2
        with:
          name: upload_url
          path: upload_url
  build:
    needs: release
    runs-on: ubuntu-latest
    container:
      image: alpine
    strategy:
      matrix:
        target:
          - fish
          - nano
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: upload_url
      - id: read_url
        run: |
          echo "::set-output name=upload_url::$(cat upload_url/upload_url)"
      - run: |
          ./${{ matrix.target }}/build.sh
      - id: find_artifact
        run: |
          ARTIFACT=$(find . -name "${{ matrix.target }}-*.tar.gz")
          echo "::set-output name=artifact_path::$(realpath $ARTIFACT)"
          echo "::set-output name=artifact_name::$(basename $ARTIFACT)"
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.read_url.outputs.upload_url }}
          asset_path: ${{ steps.find_artifact.outputs.artifact_path }}
          asset_name: ${{ steps.find_artifact.outputs.artifact_name }}
          asset_content_type: application/gzip
